### ISSUE TITLE
Config Issue and Keybinds Disappearing

### ISSUE THREAD

**Issue by ToxinZangoose** [alRex-U/ParCool#35] opened 2021-10-12 21:33 UTC
**Summary**

When updating past the June update, (1.2.2.11)
the configuration file refuses to write over the previous config file.

I have tried deleting the old config file and it does not produce the new config file in later versions.

Keybindings disappear by updating, as in, they do not appear in the controls menu and cannot be accessed unless using the earlier versions.

**Running Environment**
+ Minecraft Version: 1.16.5
+ ParCool Version: (1.2.2.11)
+ Forge Version (optional): 36.2.5

**Detail**

I have read into some of the other issues and I saw the keybinding issue for the numbers. (Trying to keybind a number key from 1-9/0 will result in an incorrect display of the key as key.keyboard[number of key])
If there's any other issue like this that others have reported, please let me know.

**Additional Data**
No crashes to be reported, just difficulties with keybinds and configs.

**Comment by alRex-U** [comment] 2021-10-15 12:41
Thanks reporting!
I have no idea why config is not produced. We need some tests for this.

**Comment by zargogo** [comment] 2022-03-04 15:36
With the newest version (as of this post) I also have the issue where the game keeps resetting my "1" key to "key.keyboard.1" (which doesn't work) and I have to manually reset it back every time I load the game. Running Parallels Windows 11 on Mac so that might have something to do with it (or not)

**Comment by alRex-U** [comment] 2022-03-04 17:08
Thank-you for commenting.
I forgot to tell you that I fixed the bug you reported.
[#14, will be fixed in newer version of this month](https://github.com/alRex-U/ParCool/issues/14)

That was because I set a mouse value as keyboard value. I think this cannot reproduce, but if it happened again please tell me.

**Closed** 2022-03-05 14:34 UTC
Labels: bug, 1.16

**Comment by Baggytrousers27** [comment] 2022-08-23 11:16
Keybinds are gone again in 1.19.2 1.0.0.0
Forge 43.1.2

[debug.log](https://github.com/alRex-U/ParCool/files/9401973/debug.log)
