### ISSUE TITLE
Infinite Stamina config does not work

### ISSUE THREAD

**Issue by aaronhowser1** [alRex-U/ParCool#159] opened 2023-04-18 05:00 UTC
**Summary**
```toml
[Stamina]
	#Limitation of max stamina
	#Range: 300 ~ 100000
	max_value_of_stamina = 10000
	#Limitation of max stamina recovery
	#Range: 1 ~ 10000
	max_value_of_stamina_recovery = 1000
	#Allow Infinite Stamina
	infinite_stamina = true
```
and yet I use up stamina when doing parkour

**Running Environment**
+ Minecraft Version: 1.19.2
+ ParCool Version: ParCool-1.19.2-3.0.0.3-B
+ Forge Version (optional):

**Comment by alRex-U** [comment] 2023-04-18 07:20
Did you enable infinite stamina on client side?

**Comment by aaronhowser1** [comment] 2023-04-21 13:55
Is it on both sides? Shouldn't it just be server side? Regardless, this was in `parcool-server.toml`, and is in fact the default value.

**Comment by alRex-U** [comment] 2023-04-22 02:33
If you want to enable infinite stamina, you have to enable it on both client and server side.

**Comment by aaronhowser1** [comment] 2023-04-23 13:06
Doesn't that seem a bit off? Why is that?

**Comment by alRex-U** [comment] 2023-04-23 16:10
> have to enable it on both client and server side 
was not a proper expression. More exactly writing, 
> Players can enable infinite stamina whenever they want to, but also hosts of the servers can disable it forcibly"
is correct. (Thus the permission of infinite stamina on server side is defaultly true, as you can see)

Anyway the problem is whether program is working as I think. Can you enable infinite stamina.

**Comment by aaronhowser1** [comment] 2023-04-23 16:17
That did indeed work. Maybe a line should be added to the serverconfig's comment like `Also has to be enabled in client config`?

**Comment by alRex-U** [comment] 2023-04-26 13:32
This config is just a permission. I think players can understand it by reading the word "Allow" in the description. Well, indeed I should write more detailed description.

At least this is not a bug so please let me close this issue.

Thanks for your suggestion.

**Closed by alRex-U** 2023-04-26 13:32 UTC
Labels: bug, question
