### ISSUE TITLE
[1.19.2] I can't get into dedicated server

### ISSUE THREAD

**Issue by DankestO** [alRex-U/ParCool#192] opened 2023-08-29 10:02 UTC
**Summary**
With the new update (ParCool-1.19.2-3.1.0.1-R) when I go to my dedicated server an error appears and it doesn't let me enter.

**Running Environment**
+ Minecraft Version: 1.19.2
+ ParCool Version: ParCool-1.19.2-3.1.0.1-R
+ Forge Version (optional): forge-1.19.2-43.2.21

**Detail**
In singleplayer everything works correctly, it only happens with dedicated servers from what I've tested.

**Additional Data**
No crash-report is produced, so I can't send that unfortunately.
![image (1)](https://github.com/alRex-U/ParCool/assets/126206944/ee290888-e0a7-4c7a-a36f-e7d496a6b417)

**Comment by alRex-U** [comment] 2023-08-30 07:03
Yeah this is already known error. I am working on fixing it.

This problem is occurs on 1.19.x - 1.20.x. I got detailed error log, but this exception was raised from io.netty networking library so I cannot know the exact cause.

I think that synchronization of command argumrnt type is probably the cause. probably. I have no clue that indicate this fact.

When I set online-mode by false in server.properties, this issue doesn't occur.

or for moment please use v3.0.x.x, not v3.1.x.x.

**Comment by alRex-U** [comment] 2023-09-01 13:26
Fixed on v3.1.0.3

**Closed by alRex-U** 2023-09-01 13:26 UTC
Labels: bug, important
